// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Eleven19.Net.Http.Formatting.Csv")]
[assembly: AssemblyProductAttribute("Eleven19.Net.Http.Formatting.Csv")]
[assembly: AssemblyDescriptionAttribute("A set of media type formatters.")]
[assembly: AssemblyVersionAttribute("0.1.5")]
[assembly: AssemblyFileVersionAttribute("0.1.5")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.1.5";
    }
}
